name = "lens"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Static assets (web frontend)
[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

# D1 Database (Metadata)
[[d1_databases]]
binding = "DB"
database_name = "lens-d1"
database_id = "af9a1e43-7c7b-47da-add7-ed16d6de5ee5"

# Vectorize Index (Semantic Search)
[[vectorize]]
binding = "VECTORIZE"
index_name = "lens-vectors"

# Workers AI (Embedding)
[ai]
binding = "AI"
gateway = "lens-gateway"

# R2 Bucket (Image Storage)
[[r2_buckets]]
binding = "R2"
bucket_name = "lens-r2"

[[kv_namespaces]]
binding = "SETTINGS"
id = "22886c458d704579b15981987dca7dc5"

# Analytics Engine (Telemetry)
[[analytics_engine_datasets]]
binding = "TELEMETRY"
dataset = "lens_telemetry"
